- docker-compose.yml
This is simply to help get a database up and running when running the application locally.
> P4-2136 adding simple docker-compose file so can easily spin up a Postgres DB

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/PriceRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsSpreadsheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheetTest.kt
Changes to tighten up the validation when importing prices for the given suppliers.  No longer relying entirely on JPA constraints.
> P4-2260 changes to tighten and improve the validation around the prices import process.

- helm_deploy/calculate-journey-variable-payments/templates/_envs.tpl
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
First pass and helm config definitions.
> Deploy config

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/reporting/MoveFilterer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGeneratorTest.kt
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Tidy up the params on the Spreadsheet generator.
Also removed mockito test resource and replace with test dependency which does the same job.
> P4-2228 change on the back of comments to tidy up the call to the spreadsheet generate method.

- helm_deploy/calculate-journey-variable-payments/templates/ingress.yaml
- helm_deploy/values-dev.yaml
> Shared ingress

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/MovePrice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/PriceCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RowValue.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/reporting/MoveReportFilterer.kt
- src/main/resources/application-dev.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/StandardMovesPriceCalculatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/StandardMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/StandardValuesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/reporting/TestReportingEntityFactory.kt
Write sitename rather than nomis agency id to the output spreadsheet.
Write NOT MAPPED rather than leaving blank, if the location type is blank.
> P4 2228 spreadsheet render site name and location type

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/MovePrice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsSpreadsheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PriceImportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheetTest.kt
These changes are primarily adding tests were they were missing e.g the importers.  Also includes some minor tidy ups in others as well.
> P4-2260 improving test coverage primarily for the importers including some other tidy ups.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/PriceCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/LockoutMovesSheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RedirectionMovesSheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RowValue.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/reporting/Journey.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/reporting/MoveReportFilterer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RedirectionMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RowValueTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/StandardMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/reporting/MoveReportFiltererTest.kt
MoveReportFilterer.kt
Add lockouts
Change multiTypeReports to filter out lockouts
RowValue.kt
Notes filtered so only show for appropriate events
Also tests for RedirectionMovesSheet.kt
> P4-2189 Write lockout moves to spreadsheet

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/InboundSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/JPCPriceBookSheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/JPCPriceBookSheetTest.kt
Small change to apply formatting to the the journey id and price columns in the JPC price tab.
> P4-2214 small changes to apply stying to the journey id and price columns in the JPC price sheet.

- helm_deploy/calculate-journey-variable-payments/templates/ingress.yaml
Adds basic-auth to the service ingress.
> Add basic-auth to the ingress

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGenerator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/TestConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RedirectionMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/StandardMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/SummarySheetTest.kt
- src/test/resources/application-test.yml
Changes include:
Updates to the outputted spreadsheet.
Cleaning up some of the unit tests.  Getting rid of unnecessary code.
> P4-2235 changes to the outputted filename and some minor refactorings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ImporterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/TimeSource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGenerator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportControllerTest.kt
Adding test coverage for generated filename.
> P4-2235 verifying outputted file name in unit test.

- helm_deploy/calculate-journey-variable-payments/templates/_envs.tpl
- helm_deploy/calculate-journey-variable-payments/templates/secrets.yaml
- helm_deploy/secrets-example.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/GeoameyPricesProvider.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ImporterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/S3ProviderConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/TimeSource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/POISpreadsheetProtection.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/SpreadsheetProtection.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/reporting/ReportingImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/TestConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PriceImportTest.kt
Changes to enable password protection of outputted calculated price spreadsheet.
There are some other minor refactoring's also included as part of this change.
Additionally included are some helm changes by @minglis for the secrets config.
> P4-2213 changes to support password protection of spreadsheet a long with some general tidy up.

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> More Memory

- .circleci/config.yml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Enable CI to deploy to preprod and prod
> Enable CI prod deployment

- build.gradle.kts
- docker-compose.yml
- helm_deploy/calculate-journey-variable-payments/templates/secrets.yaml
- helm_deploy/secrets-example.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/resources/application-localstack.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/TestConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportControllerTest.kt
This is start of integration with the HMPPS auth service.
The localstack changes has a dependency on this PR also [PECS jpc test creds](https://github.com/ministryofjustice/hmpps-auth/pull/616)
> P4-2392 intial piece of work for integrating with the HMPPS auth service.

- src/main/resources/templates/fragments/move-by-type.html
- src/main/resources/templates/fragments/summary.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveTypeWithMovesAndSummaryTest.kt
Only show pending badge if there are unpriced moves for move type / overall summary
Also, prefix prices with a leading 0 if they are less than £1
> P4-2368 summary page - pending badge

- src/main/resources/templates/fragments/move-by-type.html
- src/main/resources/templates/fragments/summary.html
Change percentage wording to %
Remove JPC version
> P4-2368 summary page - percentage and JPC version

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/FilterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/filter/ChooseSupplierFilter.kt
- src/main/resources/templates/choose-supplier.html
- src/main/resources/templates/fragments/summary.html
- src/main/resources/templates/layout/empty.html
TL;DR: Select a supplier if you haven't done so before.
Screenshots:
> P4-2402 Choose a supplier

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveType.kt
- src/main/resources/templates/choose-supplier.html
- src/main/resources/templates/fragments/summary.html
- src/main/resources/templates/layout/base.html
- Fixed "Jump to month" session attribute
- Fixed supplier name
- Amended names for move summaries
- Adjust box size and padding for total price
- Removed extra tabs
> UI amendments

- README.md
- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/OutputSpreadsheetControllerTest.kt
A small change to bring a previously disabled test (due to security changes) back online.
> P4-2452 small PR to bring disabled test back online.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/resources/static/style.css
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/fragments/list-moves-by-type.html
- src/main/resources/templates/fragments/move-summary.html
- src/main/resources/templates/moves-by-type.html
Styled the moves page.
I cannot test it because the import data doesn't work locally.
Also, the download button is currently not plugged in.
> P4-2426: List moves by type

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveType.kt
- src/main/resources/static/style.css
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/fragments/move-summary.html
- src/main/resources/templates/layout/base.html
- src/main/resources/templates/move.html
- src/main/resources/templates/moves-by-type.html
> P4-2429 Move page

- helm_deploy/values-prod.yaml
was pointing to preprod instead of prod.
> P4-2452 fixing url for auth service.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/resources/templates/fragments/header.html
This include Thymeleaf security extras which enables us to easily identify the logged in user.  It also provides additional features on top of this if needed.
For reference: https://github.com/thymeleaf/thymeleaf-extras-springsecurity
> P4-2393 change to display the logged in user.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/resources/templates/fragments/header.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/LogoutApplicationTest.kt
- src/test/resources/application-test.properties
Note this changes does not log you out of the DPS single sign on.  That will be dealt with separately in a future story/ticket.
> P4-2493 redirecting to the back to DPS on logging out from JPC session.  This does not log you out of DPS SSO.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MapFriendlyLocationService.kt
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/map-location.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
There is no way via the app at the moment to get to this page.  You can for now (once logged in) go via a get request to:
**/map-location/<PUT_AGENCY_ID_HERE>**
> P4-2493 initial commit for start of work for mapping friendly location names.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneysSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepository.kt
- src/main/resources/templates/journeys.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepositoryTest.kt
> P4-2492: Journeys for review

- .env
- src/main/resources/application.yml
Not 100% sure this fixes the dev deployment.  It does seem however that removing this config does not break the local build.
> P4-2535 config cleanup for flyway.

- src/main/resources/static/style.css
- src/main/resources/templates/fragments/header.html
The logout button is now a proper button.
> Fixed logout button

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersister.kt
> Fix counter so that it increments

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/ReportsImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/schedule/ReportsImporterScheduler.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/schedule/ReportsImporterSchedulerTest.kt
To import a singles day reports then the from and to dates should be the same.  The changes fixes that on the cron job.
> P4-2535 fixing the date for the reporting data scheduled import.

- src/main/resources/templates/search-journeys.html
> P4-2495: fixed interface for searching journeys

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MapFriendlyLocationService.kt
- src/main/resources/templates/journeys.html
- src/main/resources/templates/map-location.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MapFriendlyLocationServiceTest.kt
So this is a work in progress but should be safe to merge.  This is combining the create with the update for the friendly location names.
> P4-2514 initial work to support update of friendly location names.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/templates/add-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
First cut of persistence and validation for add prices.
This change also pulls out the add price into its own controller.
@danielepolencic feel free to merge this if you are happy with it.
> P4-2494 first curt of validation and persistence for add price.

- src/main/resources/templates/journeys.html
Changes:
- Updates the journeys for review template to show 'Awaiting location' in the pricing column if from or to site is missing.
> P4-2514 updating journey review form to show awaiting location in price column if from or to site missing.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/templates/search-journeys-results.html
- src/main/resources/templates/update-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
Changes:
- Updates to the service layer to support updates to existing supplier prices.
- Template and controller changes to integrate with the service layer.
> P4-2515 initial work to support update price in the back end.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Move.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/Money.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
Changes:
Resolves price rounding issues when add and/or updating prices by the web front end.
> P4-2515 changes to resolved a price rounding issue upon save prices.

- README.md
Expanding on the processes in place for data fed into the application. Be that automatically via CRON or manually.
> P4-2441 updating the readme around the data import processes.

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Money.kt
- src/main/resources/templates/add-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/resources/application-test.yml
Small PR with some tidy ups and test improvements around update prices.
> P4-2515 some test improvement and refactoring around prices.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/S3ProviderConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
Changes:
Primarily refactoring changes along with some fixes for the effective year (fingers crossed) for add price when invalid price entered.  The effective year still needs to be handled for the update price, I have not done this bit.
> P4-2515 tidying up the controller for add prices and extending test coverage for effective year on add price.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Money.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
Change (fix):
- This fixes a rendering issue when first going into the update price screen.  Price was in the wrong format e.g. 100.00 was displayed as 100.0
> P4-2514 fixes issue whereby price was being return in incorrect format. 100.00 would have been 100.0.

- build.gradle.kts
Change:
- flyway update not compatible.  rolled back for now.
> P4-2613 general house keeping - rolling back flywaydb change.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
Changes:
- Changes to security configuration to support session management in a clustered environment.
> P4-2518 changes to support session management in a clustered environment.

- .circleci/config.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
Changes:
- Minor change to method name and picked up latest HMPPS circleci orb.
> P4-2518 minor change, method rename and orb bump.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheetTest.kt
Changes:
- Fixes an issue whereby the price importer failed to import when it encountered a duplicate Price (from and to locations).
> P4-2646 fixes duplicate price issue spotted during import of pricing spreadsheet

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersisterTest.kt
Changes:
- Small dependency updates for fix failing OWASP job on CI.
> P4-2652 dependency updates to fix OWSASP build failures on CI job.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/PricesSpreadsheetGenerator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
Add effectiveYear to price auditing
> Fix error when adding a price while a price already exists for previous years

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/JourneyService.kt
Changes:
- Non-functional changes.  Bumping 3rd party libraries.
- Added logging where logger was specified but not used in the JourneyService.  This will aid us with some basic retrieval metrics.
> P4-2657 some house keeping bumping to later 3rd party libraries and adding some logging around journey and price retrieval.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MonitoringService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ExceptionHandlerTest.kt
Changes:
- Adding Sentry alert monitoring to raise awareness of unexpected errors occurring in the logs.
> P4-2761 adding extra (Sentry) monitoring for alerting unexpected exceptions.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/resources/templates/error.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ExceptionHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
Changes:
- Introducing a default service error page.
> P4-2690 adding default service error page.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/OutputSpreadsheetController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/filter/ChooseSupplierFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/MoveFilterer.kt
Changes:
- Adding logging to the controllers to aid with error identification in the logs in terms of what the user was trying to do at point of failure.
- Some small refactorings to clean up the controllers interaction with the model e.g. extension functions.
> P4-2690 adding logging to controllers to aid with identifying potential errors and some small refactorings.

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Non-functional changes:
- Adding 3rd party transitive constraint override as we are currently at the latest version of direct dependency Apache POI.
- Updating other dependencies to later versions.
> P4-2720 resolving OWASP CVEs.

- build.gradle.kts
Changes:
Non-functional changes.  House keeping, bumping 3rd party libraries.
> P4-2722 house keeping, bumping 3rd party libraries.

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
**Changes:**
Mainly updates to dependencies which resolves the failing OWASP check. Main OWASP dependency change is the latest version of the DPS Gradle spring boot plugin.
> P4-2736 resolving OWASP CVE's and updating 3rd dependencies.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/MapLocationMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/FakeAuthentication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
- src/test/resources/application-test.properties
- src/test/resources/application-test.yml
Changes:
Initial backend prep work for showing price changes in the UI.  A DB migration piece of work is to follow this one.
> P4-2823 refactoring the price auditing in preparation for upcoming UI changes.

- src/main/resources/db/migration/dml/V1_2__rename_price_audit_events_metadata_attrs.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/migrations/MigrationsTest.kt
- src/test/resources/db/migration/testdata/V1_1_1__price_audit_event.sql
Price auditing events migration PR following on from this previous one [here](https://github.com/ministryofjustice/calculate-journey-variable-payments/pull/256)
> P4-2823 price audit event migration in preparation for front end work.

- helm_deploy/values-dev.yaml
Enabled the incorrect CRON job in previous commit, doh!
> P4-2833 enabling (the correct) automatic mapping of locations cron job in dev for testing.

- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AutomaticLocationMappingService.kt
Changes:
Small logging enhancement for when auto mapping new locations and enabling the automatic location matching CRON job in pre-prod.
> P4-2833 enabling automatic mapping of locations cron job in preprod for testing.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/LocationHistoryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PriceHistoryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/templates/update-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/LocationHistoryDtoTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PriceHistoryDtoTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
**Changes:**
This change introduces a price history tab on the update prices page of the application.
> P4 2806 UI for price history

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/MapLocationMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ImporterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/InboundSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ObfuscatingReportImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Journey.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Move.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AutomaticLocationMappingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BasmClientApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/JourneyService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ObfuscatingReportImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/StandardMovesSheetTest.kt
**Changes:**
Resolving all deprecation warnings as a result of moving to Kotlin version 1.5.10.
> P4-2841 resovling deprecation warnings after upgrade to Kotlin verion 1.5.10

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/PriceSheet.kt
**Changes:**
Attached images to illustrate the columns affected.
> P4-2928 adjusting some of the columns widths a little to avoid text wrapping.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/PriceSheet.kt
**Changes:**
2nd attempt at tweaking columns widths (Libre Office is not behaving the same as Excel).
> P4-2928 second attempt at adjusting some of the columns widths a little to avoid text wrapping.

- README.md
- build.gradle.kts
- docker-compose.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/GotoDashboardTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ChooseSupplierPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/DashboardPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/LoginPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/migrations/MigrationsTest.kt
- src/test/resources/fluentlenium.properties
**Changes:**
This is the first cut of adding some level of integration testing to the application.  It is pretty basic at the moment but will hopefully provide a baseline to be improved upon.
At the moment this relies on the user to run the integration tests (see the readme file for details).  Ideally we would want this to go into a CI pipeline somewhere.
> P4-2906 first cut of adding integration testing.  This is a WIP.

- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/CustomHtmlUnitDriver.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/GotoDashboardTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ApplicationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/DashboardPage.kt
**Changes:**
Updated the integration tests to include coverage for the download spreadsheet link from the dashboard for each supplier.
> P4-2906 updating integration test to verify spreadsheet download is working.

- .circleci/config.yml
- src/main/resources/application-dev.yml
**Changes:**
This change introduces the integration tests as part of the CI pipeline.
Assuming the unit tests pass this part of the workflow will then be executed.  If this passes then we are done and it can be deployed.
> P4 2906 add integration tests to ci pipeline

- src/main/resources/templates/add-price.html
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/search-journeys.html
- src/main/resources/templates/select-month.html
- src/main/resources/templates/update-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ObfuscatingReportImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/CustomHtmlUnitDriver.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/GotoDashboardTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManagePricesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/AddPricePage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ApplicationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/DashboardPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/JourneysForReviewPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ManageJourneyPricePage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/SelectMonthYearPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/UpdatePricePage.kt
**Changes:**
First cut of adding integration test coverage for the add and update price scenarios.
_Note:  It isn't quite right as there is currently an issue with some drop down JavaScript not firing for location name look-ups so currently I am going direct to a URL instead of via the screen it should._
> P4-2962 initial commit for integration tests for add and update price.

- .circleci/config.yml
- README.md
- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/GotoDashboardTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManagePricesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ApplicationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/JourneyResultsPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/JourneysForReviewPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ManageJourneyPricePage.kt
- src/test/resources/fluentlenium.properties
**Changes:**
The changes in this PR now mean we are using chromedriver to drive the integration tests.  This resolves the issue around JavaScript not working (with HtmlUnit).
Both the add and update price screens now follow the correct flows through the application.
> P4-2962 using chromedriver to resolve issue with JavaScript not working. Price add and update pages now following correct path.

- src/main/resources/templates/add-location.html
- src/main/resources/templates/manage-location.html
- src/main/resources/templates/search-locations.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManageLocationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ApplicationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/DashboardPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/JourneyResultsPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/JourneysForReviewPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ManageLocationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/MapLocationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/Pages.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/SearchLocationsPage.kt
**Changes:**
This PR adds integration test coverage for the add and update NOMIS locations.
_note: some refactorings are included as part of this PR to reduce the amount of boiler plate in the actual tests which will hopefully make them a little less verbose but still clear enough to follow and understand the intentions._
> P4-2694 new integration test coverage for add and update NOMIS locations.

- src/main/resources/templates/find-move.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewMoveDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/FindMovePage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/MoveDetailsPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/Pages.kt
**Changes:**
Adding a new integration test for search for a move by its reference and viewing its details on the move details page.
This is the first cut.  I will be adding more assertions on the actual details page to verify the details.
> P4-2966 first cut of integration test to search for a move and display its details.

- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/GotoDashboardTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManageLocationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManagePricesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewMoveDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ApplicationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/Pages.kt
**Changes:**
Purely refactorings to ensure all tests are following the same (similar) patterns.
> P4-2966 refactoring changes only.  No additions.

- .circleci/config.yml
**Changes:**
Pinned the version of chrome in the integration test workflow.  There are some known issues around chrome dependencies so will wait that one out for now.
> P4-3043 pinning chrome version as this appears to have changed with the latest images from Circle.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/BulkPriceUpdateCommands.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjuster.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustment.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustmentRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceUplifter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/main/resources/db/migration/ddl/V1_10__add_table_supplier_price_adjustments.sql
- src/main/resources/db/migration/ddl/V1_9__drop_table_supplier_price_uplifts.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/BulkPriceUpdateCommandsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjusterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustmentRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsServiceTest.kt
**Changes:**
This PR is mainly refactoring in preparation for adding additional auditing at the individual price level.
Some of the renaming of classes/objects/entities has come about after a conversation with the Commercial team which has given us better understanding of their needs with respect to annual (bulk) price changes.  For example 'price uplifting' is just one type of price change/adjustment but it is a price adjustment.
> P4 3011 refactoring price adjustments for auditing

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PriceImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
**Changes:**
This PR adds support for auditing bulk price imports at the individual price level i.e. each price addition is audited as well as the process as a whole.
> P4-3011 audit prices for bulk price imports

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjuster.kt
**Changes:**
Small change to log the progress for price adjustments to aid visibility when running the bulk price adjustments from the CLI.
> P4-3083 changes to show progress for price adjustments in the logs as the process can take some time.

- .circleci/config.yml
**Changes:**
Non-functional change. Bumping to latest HMPPS Circle CI pipeline orb.
> P4-3090 housekeeping, bumping to latest version of HMPPS Circle CI orb.

- .circleci/config.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PriceHistoryDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PriceHistoryDtoTest.kt
**Changes:**
Small change for the price history tab so it is clear when a price change is the result of bulk price adjustment.
> P4 3128 price history changes for adjustments

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationInformationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/main/resources/static/style.css
- src/main/resources/templates/layout/base.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationInformationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/AnnualBulkPriceAdjustmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/AnnualPriceAdjustmentPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ManageJourneyPriceCataloguePage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/Pages.kt
**Changes:**
- Supplier level application alert to inform users if there is a supplier bulk price adjustment in place.  This displayed as the user navigates around the application the first time they navigate to a page (see screen shot below).
- Adding integration test coverage for bulk price adjustments.
> P4 3094 application information alert feature

- src/main/resources/templates/fragments/header.html
**Changes:**
Fixing issue picked up as part of the pen testing where by the username changed via XSS.
> P4-3173 change to ensure username is escaped upon rendering.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageJourneyPriceCatalogueController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/resources/templates/layout/base.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
**Changes:**
The change resolves the highlighting of the main navigation menu bar as the user navigates around the application.  Previously the navigation choice stayed on the same menu item throughout 'Move Summary'.
> P4-3006 changes to resolve the highlighting of main menu navigation bar as the user navigates around the application.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PriceHistoryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/PriceMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/static/style.css
- src/main/resources/templates/add-price.html
- src/main/resources/templates/fragments/flash-messages.html
- src/main/resources/templates/update-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PriceHistoryDtoTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/PriceMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
**Changes:**
Adds support for removal of price exceptions.  As with addition of price exceptions removal of them is audited.
> P4 3211 price exceptions remove feature

- build.gradle.kts
**Changes:**
Updating 3rd party dependencies to resolve security warnings/issues.
All tests have been run as part of this change and pass.
> P4-3235 updating dependencies where available to resolve security warnings.

- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManageLocationsAndPricesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewAllMoveTypesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/IntegrationTestDataFactory.kt
Resolves temporal bug in the test fixture setup that only came apparent as a result of the new year change.
> P4-3392 fixing a temporal issue with one of the unit tests.

- helm_deploy/calculate-journey-variable-payments/templates/_envs.tpl
- helm_deploy/values-dev.yaml
Scheduling backfill task in dev for test run prior to preprod run.
> P4-3432 scheduling backfill task in dev for testing.

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/TimeSource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/BackfillReportsTask.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/util/ExtensionFunctions.kt
Small refactoring and scheduling the backfill to run in preprod tomorrow in the morning.
> P4-3432 refactoring a long with scheduling backfill task to run in preprod.

- .github/CODEOWNERS
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/IntegrationTestDataFactory.kt
This is linked to [issue](https://github.com/ministryofjustice/calculate-journey-variable-payments/issues/403)
> P4-3468 adding code owners to repo for reviewing purposes.

- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/HistoricMovesProcessingService.kt
Disabling CRON as no longer want it in an enabled state.
> P4-3432 disable preprod cron for backfill.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/HistoricMovesCommand.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/ReportImportCommand.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/HistoricMovesProcessingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/PricesSpreadsheetGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/BackfillReportsTask.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/util/DateRange.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/HistoricMovesCommandTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/ReportImportCommandTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/HistoricMovesProcessingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/CancelledMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/JourneysSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/LocationsSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/LockoutMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/LongHaulMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/MovesSummarySheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/MultiTypeMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/RedirectionMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/StandardMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/SupplierPricesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/BackfillReportsTaskTest.kt
Dependency updates part keeping things up to date but primarily to resolve security warnings.
> P4 3472 chore security fixes

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/filters/ChooseSupplierFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/filters/FilterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationInformationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ControllerExtensionFunctions.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ControllerSessionAttributes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/JourneyPriceCatalogueController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageJourneyPriceCatalogueController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PrimaryNavigationBar.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/SessionAttributes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/SummaryPageController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/filters/FilterConfigurationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/SummaryPageControllerTest.kt
Mainly tidying up the controllers.  HtmlController is no more, yay!.
Also tidied up the primary navigation logic to make it a little clearer (hopefully) as to how it works,
> P4-3489 refactoring the controllers.

- .circleci/config.yml
Removing this var in hopes that the circleci builds will pass now
> Remove HELM_VALUES_FILE var

- helm_deploy/values-dev.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/moves/HistoricMovesProcessingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/ReprocessExistingMovesTask.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/ReprocessExistingMovesTaskTest.kt
This changes the task to log the number of specific move types before and after it is run. 
This change also includes a change to run the task at 15:30 today on dev.
> P4-3530 refactoring task to log the number of moves types before and after the scheduled task is run.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceExceptionRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/PriceSheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/PricesSpreadsheetGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/SupplierPricesSheet.kt
- src/main/resources/db/migration/ddl/V1_20__add_indexes_to_prices_and_moves.sql
- src/main/resources/db/migration/dml/V1_19__add_month_and_year_values_to_moves.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/PricesSpreadsheetGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/SupplierPricesSheetTest.kt
Further performance enhancements.
Some incremental, addition of new indexes to help with queries.  The other main change to the way prices add added to the generated spreadsheet for the price catalogue, this was particularly slow.
> P4 3559 performance improvements v2

- build.gradle.kts
Chore to bump 3rd party dependencies.
> P4-3758 bumping 3rd party dependecies to latest versions where applicable.

- scripts/bulk_price_upload/README.md
- scripts/bulk_price_upload/delete-rds-snapshot.sh
- scripts/bulk_price_upload/list-rds-snapshots.sh
- scripts/bulk_price_upload/take-manual-rds-snapshot.sh
Added bash scripts to assist with listing, creation and removal of snapshots when doing a bulk price upload operation.
> P4-3670 adding scripts to help with listing, taking and deleting snapshots.

- scripts/bulk_price_upload/README.md
- scripts/bulk_price_upload/run-bulk-price-upload.sh
This change includes a small text correction on the back of the previous PR.
It also adds a prompt to check an RDS backup has been done and the spreadsheet with the prices has been uploaded to S3 prior to attempting to import them.
> P4-3782 small textual change due to previous PR comment and adding prompt to check RDS backup done and spreadsheet uploaded.

- .circleci/config.yml
- build.gradle.kts
- docker-compose.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/AnnualBulkPriceAdjustmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/LodgingPriceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManageLocationsAndPricesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/MovePriceExceptionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewAllMoveTypesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewMoveDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ApplicationPage.kt
- wiremock-docker/docker-compose.yml
This is temporally fix to move forward with:
- Switching security alerts to Github actions
- Security update
The following action will be taken after that
- Update hmpps-external-users-api to the newest version
- Run all integration tests in specific order by Grade not by CircleCi
- Reduce logs generated by Selenium webdriver
- Review how useful is to have a screenshot when tests are failing 
(Remove functionality or improve code by using TestWatcher)
> MAP-1872 fixing main branch

- helm_deploy/calculate-journey-variable-payments/values.yaml
temp add repo var to run Trivy scans
> MAP-1956 repo env fill at values.yaml

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
Fixes https://dsdmoj.atlassian.net/browse/MAP-2033
> Enables scheduled downtime for preprod and dev
