- .gitignore
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationTab.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationTypeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationTabTest.kt
This change maps the incoming schedule 34 location types to a set of agreed abbreviations which will ultimately end up in the generated calculated journey pricing spreadsheets for a given supplier.
> P4-2237 this change maps the imported location types to abbreviations which will end up in the generated spreadsheet.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/importer/LocationsSpreadsheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheetTest.kt
These changes tighten up the location validation steps when importing the locations spreadsheet.
Persistence level exceptions have been reduced as we are now checking prior to save the locations entity in the DB.
The locations import will also fail (fast) if any of the expected location spreadsheet tabs are missing.
> P4-2170 changes to tighten and improve the validation around the locations import process.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/MovePrice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/PriceCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PriceSheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RowValue.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/StandardMovesSheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/calculator/StandardMovesPriceCalculatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/StandardMovesSheetTest.kt
Not pretty, but functional
Create RowValue.kt to hold the display value for each cell
Add fromLocationType and toLocationType to MovePrice.kt
Create an addStandardRow fun on PriceSheet.kt which StandardMovesSheet uses
> p4-2186 add columns to standard moves sheet

- Dockerfile
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ImporterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/JCPTemplateProvider.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/PricesSpreadsheetGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/RedirectionMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/output/StandardMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PriceImportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/pricing/importer/PricesSpreadsheetTest.kt
This PR was originally primarily to improve some of the overall performance when importing prices.  In doing so this did highlight a few things that needed attention.  In particular the way the JCP template spreadsheet was being supplied (as a File) using the Spring ResourceLoader meant it could not be detected with in the deployed JAR.  To load files from the JAR itself you need to load them as an input streams.  This should now be resolved so there is no need to copy to a separate file location in the Docker file.
> P4-2214 tuning mainly around price import but also some refactoring.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/JpcApplication.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/import/LocationAndPriceImporter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/import/LocationAndPriceImporterTest.kt
The driver for this change is so we can run an import of locations and prices via direct call to jar file and negate the need to go via a rest call.  This should enable us to then call via a cron job for example.
> P4-2434 adding ability to run an import on application start.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/import/price/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ImportControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/import/LocationAndPriceImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/importer/PriceImportTest.kt
This changes means locations and prices can only be imported from the commandline going forwards.
@mafonso this change should mean going forwards we will not be restricted to one pod as this can be run via a cron job in a controlled manner.
> P4-2434 removed endpoints for importing locations and prices.  This can now only be done via the commandline.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/JpcApplication.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/import/SupplierReportsImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/import/LocationAndPriceImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/import/SupplierReportsImporterTest.kt
This is part two of moving imports (of reports) to the command line.
The following commandline parameter has now been added, see example below:
`--import-supplier-reports=2020-10-01,2020-10-02`
> P4-2434 changes to support running the import of supplier reports from the commandline.

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/OutputSpreadsheetController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/OutputSpreadsheetControllerTest.kt
This changes means you you can only import supplier reports from the command line going forwards, for example:
`java -jar app.jar --spring.main.web-application-type=none --import-supplier-reports=2020-10-01,2020-10-02`
> P4-2434 removal of import supplier reports endpoint as to be run via commandline.

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/FilterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/constraint/MonthYearConstraintValidator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/constraint/ValidMonthYear.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/filter/ChooseSupplierFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportDateParser.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportDateTimeParser.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/util/MonthYearParser.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/ChooseSupplierFilterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/util/MonthYearParserTest.kt
Relatively low impact changes.  This removed some compilation warnings and also increases the number of pods from 1 to 2.  The report generation is still very memory intensive so don't want to go any higher.
This branch also include a fix for the jump to month page.
> P4-2452 cleaning up some compilation warnings and increasing number of pods.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/LocationAndPriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceRepository.kt
Not able to prove this locally.  Need to deploy to see if this resolves an out of memory issue when importing locations and prices spreadsheets.  Will revert if it doesn't.
> P4-2452 flushing data after each repository call in effort to reduce memory footprint.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/JpcApplication.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/ManualLocationImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/ManualPriceImporter.kt
As it stands keeping the import of locations and prices in one call is causing out of memory errors when running on the container.  This splits out each import into a separate call to try and avoid this.
> P4-2452 splitting out the imports further in effort to stop out of memory errors.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/resources/templates/add-price.html
- src/main/resources/templates/select-month.html
> P4-2494: Add price

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/constraint/JourneySearchConstraintValidator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/constraint/ValidJourneySearch.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/DistinctJourney.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyWithPrices.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/JourneyService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/JourneysSheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/PricesSpreadsheetGenerator.kt
- src/main/resources/templates/fragments/journey-summary.html
- src/main/resources/templates/fragments/journey.html
- src/main/resources/templates/journeys.html
- src/main/resources/templates/layout/base.html
- src/main/resources/templates/layout/empty.html
- src/main/resources/templates/move.html
- src/main/resources/templates/no-search-journeys-results.html
- src/main/resources/templates/search-journeys-results.html
- src/main/resources/templates/search-journeys.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/TestConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/JourneysSheetTest.kt
Allow searching for one or two journeys.
No results page if there are no results.
Initial listing of results - but the rest of the work is for a different story
Fix move detail prices being in pence rather than pounds
Plus some other misc fixes for loading JS, rendering journeys.
> P4 2512 search jpc journey

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SchedulerConfiguration.kt
- src/main/resources/db/migration/V1_1__shedlock.sql
Using incorrect script for the shedlock table.  Needs a primary key.
> P4-2535 correcting the sql script for the shedlock table.

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Moving time of the job to be 1 hour later to avoid collision with the BaSM S3 feed.
> P4-2535 changing cron for report data import from 3am to 4am as this clashes with the S3 feed which it needs.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/constraint/DuplicateLocationConstraintsValidator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/constraint/ValidDuplicateLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MapFriendlyLocationService.kt
- src/main/resources/templates/add-price.html
- src/main/resources/templates/fragments/journey-summary.html
- src/main/resources/templates/journeys.html
- src/main/resources/templates/map-location.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
Changes:
- Move summary page - 'Total moves by journey' renamed to 'Journeys for review'
- Wires in the navigation to the map location page from the journeys for review page.
- Displays the NOMIS agency ids instead of '**Not mapped**' in the journeys for review page.
@danielepolencic this addresses some of the issues Sangeetha has raised (I'll try and look at some more).
> P4-2514 adding links to navigate to map location.  Also fixing some of the back and cancel links to go back to journeys for review page.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommands.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/ImportCommandsTest.kt
Changes:
This changes the manual import-reports command to load days individually instead of trying to do all in one go to avoid potentially using larges amounts of memory if the import spans days, weeks or months.
> P4-2441 tweaked the report import command to load days individually instead of trying to do it all in one.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Journey.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersisterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/TestMoveFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceTest.kt
Update Price and Journey so they have an effective year.
Default this to 2020 for the current spreadsheet price importer.
Change journey and move queries to require the join on journey / prices to include effective_year
MovePersister persists effective_year to journey based on:
journey start event or, if not present
move date or, if not present
the current date
> P4-2530 Effective Date

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/JourneyService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepositoryTest.kt
Manage JPC should show all pricing, including for journeys that haven't been made.
This commit addresses that by removing the journeys table from the query.
Also, Manage JPC now takes effective year from the currently selected year.
> Fix Journey Search

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommands.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommandsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/filter/ChooseSupplierFilterTest.kt
Period.between(from, to).getDays() only returns the days portion.  Eg. if your daterange is 3 months and 10 days then you would get just 10 days.
> P4-2441 resolving days in daterange.  Should use ChronoUnit.DAYS and not Period.getDays()

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
This fixes an issue whereby supplying a blank friendly name when running the application in the IDE the desired validation behaviour occurs.  However if failed when running as a standalone JAR.
A bit of digging and came across a known issue when using Thymeleaf and Spring Boot [here](https://github.com/spring-projects/spring-boot/issues/1744)
> P4-2514 fixing issue with template resolution.  Old method worked in IDE but not standalone JAR.

- .env
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/EventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Journey.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Persister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersister.kt
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- src/main/resources/templates/move.html
**ddl-auto set to create - will re-create all database tables**
Improve import speed: add batch select of moves and associated journeys and events in chunks of 100
----
Unsuccessful (but non-harmful) attempt to batch inserts / updates by adding the following to application.yml:
properties:
hibernate.jdbc.batch_size: 5
hibernate.order_inserts: true
hibernate.order_updates: true
hibernate.jdbc.batch_versioned_data: true
hibernate.generate_statistics: false
In conjunction with applying saveAll to a collection of entities.
MovePersister successfully improved to batch select moves and associated journeys and events in chunks of 100
Add move_id index to Journey
Add eventable_id index to Event
Fix bug in move.html where the Journey Event JSON was being displayed if there was only a single …
> P4-22533 Improve import

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveService.kt
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/find-move.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportMoveTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/TestReportFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/TestMoveFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/CancelledMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/JourneysSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/MovesSummarySheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/RedirectionMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/StandardMovesSheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/spreadsheet/SupplierPricesSheetTest.kt
**This adds a link to "search moves by move reference ID" on the move summary page**
New findByReference method in MoveRepository
Used by findMoveByReference in MoveService
HtmlController has new findMove GET and performFindMove POST methods
The reference is validated. Unsuccessful search redirects back to the find a move search form with appropriate message.
Successful search redirects to the moves details page for the found move_id UUID
Queries for GET move and find move now restrict by supplier.
Add 404 page to return if a move doesn't exist (for that supplier)
> P4-2529 Search by move reference ID

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersister.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersisterTest.kt
Changes:
The `MovePersister` was using the year of the move date if present but not taking into account the effective year.  This change applies the effective year logic to the move date if and when it is used to determine the effective year for journeys.
> P4-2601 resolving issue whereby the incorrect effective year is persisted for Journeys.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommands.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommandsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersisterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveServiceTest.kt
Changes:
- Journeys are now ordered by the pickup time for a move upon retrieval for displaying on the move details page.
- Update tests to verify the ordering is applied at time of retrieval in the service layer.
- Some minor refactorings and tidy-ups done as well.
> P4-2613 changes to fix journey ordering in the move detail screen.  Also some minor refactorings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/TestMoveFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveServiceTest.kt
Changes:
- Order the the journey events based on their pickup time for the presentation layer.  Was originally just using the order in which they were pulled from the DB hence sometimes it worked and other times it didn't.
> P4-2613 resolving the ordering of journey events. Was using the order they were pulled from the DB.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersister.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersisterTest.kt
Changes:
- The profile and people persister was committing for every iteration of a loop (for an entity) instead of persisting every 1000 entities.  This change moves the final commit out of the loop to prevent this from happening.
- Updated unit tests to verify the number of times the commit is invoked.
> P4-2623 fixing the profile and person persister.  Fixing the commit points.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersister.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersisterTest.kt
Changes:
- Refactoring the import and persistence of profiles and people.
- As part of the refactoring I have reduced the batch size at which entities are flushed to the DB to every 500 instead of 1000.
> P4-2623 refactoring the profile and person persister used during the report import process.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersister.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationSecurityTest.kt
Changes:
- Reduced session inactivity timeout to 30 mins.
- Max concurrent sessions for a user limited to one.
- Sessions are now automatically invalidated for any logins that fail.  Instead of waiting for the Spring background cleanup process.
- Session times now redirect back to the auth service.
> P4-2518 changes to clean up session handling e.g. timeouts, max concurrent sessions etc.

- applicationinsights.json
Changes:
- The original file where this was taken from in the dps gradle spring plugin had the wrong log level.  This change corrects it.  In truth is has little impact at this point in time as we are not using Application Insights at time of writing.
> P4-2518 correction after issue with log level was spotted release notes in the DPS gradle plugin.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Journey.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/JourneyWithPrice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Move.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovesSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Money.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/MoneyTest.kt
Changes:
- This fixes an issue whereby the incorrect rounding was being applied to prices.  It was not applying round up at 5 or above and down below 5.
- All rounding related operations moved to the existing Money class so now done in a central place.
> P4-2645 resolves issue with incorrect rounding of prices.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveQueryRepositoryTest.kt
Changes:
- Updated query to retrieve moves for viewing in the application to only fetch complete and/or cancelled moves i.e. moves which have a move_type and are not null.
> P4-2654 updating move query to exclude moves without a move type.  These are incomplete (unpriced) moves in JPC.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveServiceTest.kt
Changes:
- Show a consistent error message to the user when searching for a move (that has no move type).
> P4-2652 excluding moves with null move types from the move lookup functionality.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Journey.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/Move.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/main/resources/db/migration/ddl/V1_2__alter_column_lengths.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersisterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MoveRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersisterTest.kt
Changes:
- Increase lengths of certain DB columns that caused the failure of the importer due to being too long (using DB migration).
- Reworked the MovePersister to not fail and exit if an move fails to import.  It will skip any bad moves.
- Move the MovePersister away from batch importing of moves.  Will now push a single move to the DB with is relevant other data.
- Reduced the batch size of the Person/Profile importer (Will actually look at moving away from batch inserts in a separate PR).
> P4-2666 changes to (fix) improve the robustness of the move import process.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/LogInAuditHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/LogOutAuditHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommands.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/OutputSpreadsheetController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/MovePersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/move/PersonPersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/schedule/ReportsImporterScheduler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BulkPricesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MapFriendlyLocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/TestConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommandsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/schedule/ReportsImporterSchedulerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BulkPricesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
Changes:
- Auditing of imports a long with some refactorings.
- I have removed the ability to specify a date range at the service level when importing reports.   Due to large volumes of data we should only be doing one day at a time.
- Some tweaks around auditing e.g. tidying up the meta data to use snakecase which is more in line with JSON.
- Some tweaks to the auditable events also.  Removed timesource (I know this was my suggestion originally) as just too noisy.
- I think there is still some possible tidy up needed around the authentication.  If it is needed then it shouldn't be nullable via the interface.
> P4 2657 import auditing

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/LogInAuditHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/LogOutAuditHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/OutputSpreadsheetController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BulkPricesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MapFriendlyLocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SpreadsheetService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/OutputSpreadsheetControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SpreadsheetServiceTest.kt
Changes:
- Fixing issues with the download spreadsheet where can use free text for supplier.
- Shifted the auditing of the spreadsheet download into the service so this is captured where it might take place.
- Shorted the build function names in the AuditableEvent.  
- Testing locally I spotted I had missed the report_date from the importing of reports. Also added missing test coverage.
> P4-2657 futher changes to include report date (a long with some refactoring) to audit imports.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MonitoringService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
Changes:
- First cut at sending messages to Sentry IO monitoring service should there be any persistence failures during the importing of reporting data - moves, people and profiles.
> P4-2761 adding simple free text monitoring around reports import whenever a persistence failure occurs.

- docker-compose.yml
Changes:
- Minor change to docker-compose file to pin to a specific DB version to avoid potential versioning issues/incompatibilities with the RDS instances in dev, preprod and prod.
> P4-2611 pinning db version to be in-line with RDS to ensure no compatibility issues.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PriceImportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PricesSpreadsheetTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
Changes:
- This changes the price importer to check existing prices effective year.  Without this we can get duplicate errors when really there shouldn't be.  For example we can have a 2019 price in the system where the **from** and **to** are the same as a 2020 price we are trying to import, this is not a duplicate!
> P4-2675 changes to fix an issue with the price importer throwing a duplicate price exception.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/FilterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/filter/ChooseSupplierFilter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/filter/ChooseSupplierFilterTest.kt
Changes:
So I have spent a bit of time trying to get to the bottom of this issue.  From what I can gather it only happens on the choose supplier screen.  I am not able to recreate it in my local development environment.
Looking at the code there may (possibly) be a race condition, this is an educated guess at this point.  So I have moved some of the logic closer to where it is actually needed/used.  The logic in question adds the chosen supplier to the users session (which ultimately gets persisted to the database session) and is then used straight after that by doing a redirect having chosen the supplier.  My suspicion is the time to persist it to the DB session and the point it is next used (it pulls it back from the session) after the redirect is the issue.
So as mentioned it is an …
> P4-2696 changes to (hopefully) fix a session related issue on the choose supplier screen

- docker-compose.yml
- wiremock-docker/__files/basm-api/locations/COURT1.json
- wiremock-docker/__files/basm-api/locations/COURT2.json
- wiremock-docker/__files/basm-api/locations/PRISON1.json
- wiremock-docker/__files/basm-api/locations/PRISON2.json
- wiremock-docker/mappings/basm_api_location_COURT1.json
- wiremock-docker/mappings/basm_api_location_COURT2.json
- wiremock-docker/mappings/basm_api_location_PRISON1.json
- wiremock-docker/mappings/basm_api_location_PRISON2.json
Introducing stubbed BaSM API for local development.  This is just to support calls for locations based on their NOMIS agency id.
> P4-2710 initial work for putting in WireMock so we can fake the BaSM API calls when running locally.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ImporterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/NomisReferenceDataProvider.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AgencyDetailsService.kt
- src/main/resources/spreadsheets/nomis-locations.csv
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AgencyDetailsServiceTest.kt
Changes:
This is to support the upcoming UI changes to display NOMIS location names when mapping NOMIS agencys IDs for journeys without an already mapped location name.
For now we are pulling the mappings from a CSV file.  A possible future change is to pull this from the BaSM API subject to some API changes.
It is possible there will be some mappings missing from the CSV file but this should cover most cases.
> P4-2714 new service to load in the nomis location refrence data to help with agency id mappings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MapFriendlyLocationService.kt
- src/main/resources/spreadsheets/nomis-locations.csv
- src/main/resources/templates/map-location.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
Changes:
Displays the NOMIS location name (if one can be found for the selected agency ID) on the add/update mappings screen to help the user when mapping a Schedule 34 location name.
> P4-2701 changes to UI layer to display the NOMIS location name when mapping an agency without a Schedule 34 mapping.

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
**Changes:**
Changing morning report imports to run at 5:30am (instead of 4am) to leave sufficient gap for when the files are available for actual import.
**Why was this needed?**
There was a gap of an hour between the files being uploaded (by a separate process) and then being downloaded by the application. When the clocks changed both processes ran at the same time.  This was due to one process running in UTC and the other in BST.
> P4-2728 moving report imports to run later in the day.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MonitoringService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/TestConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
**Changes:**
We will now get Sentry alerts if any of the reporting feeds fail or there are any instances where we have zero moves, people or profiles to persist for a given reporting feed date.
> P4-2727 changes to raise a Sentry alert if any of the reporting feeds fails or there are zero moves, people or profiles to persist for a given day.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/templates/error/403.html
- src/main/resources/templates/journeys.html
- src/main/resources/templates/search-journeys-results.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ExceptionHandlerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceIntegrationTest.kt
**Changes:**
This change introduces additional role requirements for those users who can add and update journeys prices.
The changes have a dependency on a change to the HMPPS Auth service ([new role](https://github.com/ministryofjustice/hmpps-auth/pull/831)) being rolled out.  At time of writing this has been approved/merged and should be available in DEV.
> P4-2723 initial commit to enforce a new price maintainer role for price maintenance.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationType.kt
- src/main/resources/templates/manage-location.html
- src/main/resources/templates/map-location.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
**Changes**:
Now iterates over available location types from the actual enum type instead of hard coding directly in the template.
> P4-2725 removing some duplication by iterating over location types from code instead of hard coding all into template.

- build.gradle.kts
- calculate-journey-variable-payments-suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
At time of reviewing there are no more up to date libraries for this CVE i.e. we are stuck with what we versions we have.  Action taken is to suppress the warning for now, it it not something likely to affect CJVP anyway.   Actual CVE can be found [here](https://nvd.nist.gov/vuln/detail/CVE-2021-29425).
To exercise it requires the user to supply a file name path in a particular format and utilise the specific function/method in the affected library.
CJVP does not provide this to the end user or use the affected function/method.
> P4-2797 suppressing OWASP CVE and updating to later libraries where available.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/MapLocationMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/MapLocationMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BulkPricesServiceTest.kt
This PR lays out the initial groundwork for sanitising the auditing metadata for Schedule 34 location mapping and remapping.  This is needed to make it easier to extract the auditing information for use in the presentation layer for location mapping history.
Further work will be needed when this has been merged to go back and update already existing location audit records to reflect the changes to the metadata structure, this will be most likely via a DB migration.
> P4-2597 initial commit for prepping the audit changes for displaying location history.

- calculate-journey-variable-payments-suppressions.xml
Changes:
Suppressing CVE-2020-7791.  It is a false positive.  See [here](https://github.com/turquoiseowl/i18n/issues/387).
> P4-2834 suppressing false positive CVE-2020-7791. It is actaully a C# CVE.

- src/main/resources/application.yml
Changes:
Reversed JPA config change.
This was originally done to remove a application startup warning but may have had an undesired effect on the spreadsheet download.
> P4-2839 reversing out config change as this may be having a knock on effect with the spreadsheet download.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BasmClientApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BasmClientApiServiceTest.kt
- wiremock-docker/__files/basm-api/locations/MULTIPLE.json
- wiremock-docker/docker-compose.yml
- wiremock-docker/mappings/basm_api_location_MULTIPLE_ON_DATE.json
Changes:
This first piece of work deals with extending the internal API which talks to BaSM to support retrieving locations added on a specific date.  This will  be invoked by a (yet to be added code based) CRON job which in turns makes calls for the previous days additions so they can automatically be added to CJVP without user (manual) intervention.
> P4 2832 retrieve new locations added to basm

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/BasmClientApiCommands.kt
- wiremock-docker/__files/basm-api/locations/MULTIPLE.json
- wiremock-docker/mappings/basm_api_location_MULTIPLE_ON_DATE.json
**Changes:**
- Adding command to the CLI so we can automatically backdate a location from BaSM.
- Some small tweaks to the WireMock files just to make local manual testing a bit easier.
> P4-2833 providing the ability to automatically backdate locations from BaSM via the CLI tooling.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BasmClientApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AutomaticLocationMappingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BasmClientApiServiceTest.kt
- wiremock-docker/__files/basm-api/locations/MULTIPLE.json
**Changes:**
This change removes the unnecessary parsing of the **created_at** date/timestamp in the response from the call to BaSM locations reference data.  We don't actually care or use it.
> P4-2833 removing redudant date parsing from location call on return fom call to BaSM endpoint.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AutomaticLocationMappingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AutomaticLocationMappingServiceTest.kt
Changes:
Through testing discovered that need to check on the site name as well as the agency id to see if a location already exists in JPC prior to auto mapping from BaSM.  Found that a site name existed in JPC with a different agency id to that in BaSM but the actual location names were the same.
> P4-2833 updating the duplicate location check prior to auto mapping new location to check on name as well as agency id.

- helm_deploy/values-prod.yaml
Changes:
Turn on the CRON job in production to run at 3:30am to automatically map locations in BaSM to locations in CJVP if it does not already exist in CJVP.
> P4-2833 enable cron to run at 3:30 am in morning for automatic location mapping task.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/LocationHistoryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsService.kt
- src/main/resources/templates/add-location.html
- src/main/resources/templates/manage-location.html
- src/main/resources/templates/update-location.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageSchedule34LocationsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MapFriendlyLocationControllerTest.kt
Changes:
When updating a location the user user is presented with a tabbed view.  One tab for updating the location and another tab for the location audit history/changes.
> P4 2805 display location history

- src/main/resources/db/migration/dml/V1_3__backfill_location_audit_events.sql
Changes:
Updating location history event migration SQL to include the event type as part of the filter.  Without this it was picking up price events and as a result not adding the entry i.e. nothing was being added if a location had a price change.
> P4-2895 tweaking migration to filter on the event type, if there was a price change then this was causing it to exclude add a default entry.

- src/main/resources/db/migration/dml/V1_4__backfill_price_audit_events.sql
**Changes:**
Audit functionality was added prior to some prices being added by the system (CRON job).  As a result this migration will insert rows for those prices which have no audit entries, if it has an entry already then no entry will be added.
This is done so we have at least one entry on the prices history tab.
> P4-2896 migration to backfill any missing audit price history for prices added prior to introduction of audit functionality.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/db/migration/ddl/V1_5__add_audit_events_event_type_idx.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
**Changes**:
The is the first attempt to improve the read time of the audit history events.  I don't want to do too much at this point so only making minor changes.  Adds an new index and removes some unnecessary string santisations.
> P4-2896 changes to improve the performance when reading the audit history events.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/MapLocationMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/LocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/db/migration/ddl/V1_6__add_column_to_audit_events_to_improve_read_performance.sql
- src/main/resources/db/migration/dml/V1_7__backfill_join_column_price_audit_events.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/MapLocationMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
**Changes:**
This change is an effort to reduce the time taken reading audit history events in the UI.  This has come about after learning how many price audit events there are.
This change adds a new column which essentially pulls out the key from the metadata which in turn can be queried on directly in the SQL instead of reading into the application and then applying the filter (which is slow).
> P4-2896 adding extra indexed column to the audit_events entity to speed up audit entry reads.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/location/LocationType.kt
**Changes:**
This change introduces a new location type 'Coroners Court' to the LocationType enum for selection in the add and update location screens.  No UI specific changes are needed, the enum is used in the template so it will automatically be available with this change.
> P4-2844 adding new location type coroners court.  This will automatcally be picked up by the UI template.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SpreadsheetService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SpreadsheetServiceTest.kt
**Changes:**
These changes make it easier to keep track of spreadsheet download failures at the user level.  Prior to this we would we receive an alert but not know who had attempted it.
> P4-2848 changes to audit spreadsheet download failures.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/ImporterConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ObfuscatingReportImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ReportImporter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/report/ObfuscatingReportImporterTest.kt
**Changes:**
This introduces the ability to obfuscate PII when running the reports import process.  In its current form it will obfuscate when running a backfill process using the CLI tooling locally.  It does not affect the test data migrations.
The driver for this change is so we can use live (PII) data locally but obfuscated to aid with performance tuning.
**Additional Info:**
This has been tested locally.
> P4-2875 initial commit for PII obfuscation when running locally.

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/SecurityConfiguration.kt
**Changes:**
House keeping.
This is the first PR to move to v1.5 of Kotlin and resolve OWASP build failure (3rd party dependency updates).
I am splitting this into a few PR's as there are some deprecation warnings as a result of moving to a later version of Kotlin.  For now this will fix the OWASP,
> P4-2841 updates to 3rd party dependencies and OWSAP resolution, thereare some deprecation warnings but will look at separately.

- build.gradle.kts
**Changes:**
Bumping Sentry monitoring API up a major version number.
I have tested this via the application CLI to ensure messages can still be sent by the application.
> P4-2841 bumping up Sentry a major version.  Tested to makesure no side effects.

- .circleci/config.yml
Updates the OWASP job to use the one from the HMPPS orb and specifies it should post to the pecs_dev slack channel on failure.
> chore: Use HMPPS Orb owasp check and post to pecs dev channel

- Dockerfile
**Changes:**
Adding missing font file to the docker image build to resolve the following error when using Apache POI
```
Caused by: java.lang.UnsatisfiedLinkError: /usr/local/openjdk-11/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
at java.base/java.lang.System.loadLibrary(System.java:1873)
```
> P4-2928 adding missing font file package to the Docker image.

- Dockerfile
**Changes:**
This addition to the Dockerfile fixes the following error when trying to download the spreadsheet.  This has been tested  by starting the container locally and then downloading a sample spreadhsheet.
```
Caused by: java.lang.NullPointerException: null
at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:379)
at java.base/java.security.AccessControlleCaused by: java.lang.NullPointerException: null
at …
```
> P4-2928 futher font file required that does not come package already with the container.

- build.gradle.kts
**Changes:**
Small change to resolve OWASP CVE's CVE-2021-31812, CVE-2021-31811.
Only option at moment is to bump transitive dependencies as main library (Apache POI) that pulls it in has yet to be updated.
> P4-2947 bumping transitive dependency to resolve OWASP CVE's CVE-2021-31812, CVE-2021-31811.

- build.gradle.kts
**Changes:**
OWASP related security change to use the latest version of the 3rd party DPS Gradle Spring Boot plugin library.
`./gradlew dependencyCheckAnalyze` has been run locally before and after the change. Red before green afterwards.
Further details related to the CVE can be found here [CVE-2021-27568](https://nvd.nist.gov/vuln/detail/CVE-2021-27568).
_Note: once this is released to production and the job is green we can close the associated JIRA ticket._
> P4-2986 bumping to the latest verions of the DPS Gradle Spring Boot plugin to resolve CVE-2021-27568.

- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewMoveDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/FindMovePage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/IntegrationTestDataFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/MoveDetailsPage.kt
**Changes:**
Fleshing out the integration test for retrieval of a move and viewing its details.
The assertions themselves are fairly crude but provide a reasonable baseline for coverage of this piece of functionality.
> P4-2966 adding page assertions for the move details upon retrieval.

- build.gradle.kts
- src/main/kotlin/db/migration/data/dev/R__2_5_Integration_test_data.kt
**Changes:**
A code based migration to assist with both development and integration tests. At the moment it will generate standard moves only for the day on which it is run.  I will be adding test data for all move types.
This enables me to easily control the dates of the individual moves so I can determine what things should like for integration tests purposes given they are very much time based.
As a bit a plus this also means we can generate current data (i.e. for the current month) when developing locally.
Attached screenshot is an example of what you would currently see running the application locally:
> P4-2967 this is a work in progress - it is a code based migration to assist with development and integration tests.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/BulkPriceImportCommand.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommands.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PriceImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/EffectiveYear.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/BulkPriceImportCommandTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/ImportCommandsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/importer/price/PriceImporterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/EffectiveYearTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
**Changes:**
- We no longer delete existing prices prior to a bulk price upload to the service.  This is so we do not loose any prices that have been manually added by the users on the front end.
- We now need to specify the effective year when uploading bulk prices.  Prior to this the system determined the current effective year at time the import was executed. This change is needed because the journey back-fill for the current contractual year is likely to **not** be completed by the suppliers in September 2021.
> P4 3012 refactor bulk price upload to add journeys and prices rather than delete and read all journey prices

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceUplifter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceTest.kt
**Changes:**
Small refactoring to move the actual price uplift (adjustment) change into the actual entity to ensure only the relevant attributes are changed.
> P4-3008 moving logic for price adjustment for new prices (not updates) into the Price entity.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjuster.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BulkPricesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjusterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/BulkPricesServiceTest.kt
**Changes:**
This is part 1 of two changes around price auditing.  This one is for price uplifts only.
This now audits each individual price adjustment (uplift) as well as the overall price uplift process.
Part 2 will be adding auditing for bulk price uploads.
> P4-3011 changes to audit price uplifts at the individual price level i.e. each price adjustment is audited as well as the process as a whole.

- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/LoginPage.kt
**Changes:**
The login URL for auth has changed to 'sign'in' (note this only affects the integration tests).
The integration tests need to be updated to use the new URL.  This only affects one class and the change is small
This ..
```
@PageUrl("http://localhost:9090/auth/login")
class LoginPage : ApplicationPage() {
```
Becomes ...
```
@PageUrl("http://localhost:9090/auth/sign-in")
class LoginPage : ApplicationPage() {
```
> P4-3050 small change to auth url in integration test to match that of change to the actual auth service.

- src/main/resources/db/migration/dml/V1_11__backfill_price_audit_events.sql
**Changes:**
Historically bulk price uploads have not been audited.  This left a gap in the price history when viewing the price history for a given journey on the front end UI.  This migration clears that up.
_Note: auditing has now been added to bulk price changes going forwards so any future uploads will be audited._
> P4-3046 migration to bring individual prices for previous unaudited bulk price uploads upto date.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjuster.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustmentRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjusterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustmentRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
**Changes:**
If an attempt is made to add or change a price whilst a bulk price adjustment is in progress for a given supplier then a runtime exception will be thrown preventing the add/update from taking place.
The error itself is caught by the application level exception handler which in turn directs the user to the general error page.
As it stands this change should be sufficient as a first cut.  Strictly speaking it will be the commercial team (who are responsible for price changes) asking us to run the bulk price adjustment in the first place until the front end screens for bulk price adjustments are available to them.
> P4-3084 changes to prevent supplier level price changes if a price adjustment is in currently in progress.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjuster.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjusterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsServiceTest.kt
**Changes:**
**_Note: this is part one of two PR's next one for refactoring, will be changing references to uplift to become adjustment based._**
Testing from the front end for locking down price changes highlighted a bug in the locking logic to prevent price changes from happening if a bulk price adjustment is in progress.
This was a (DB) transaction boundary issue which this change resolves.
> P4-3084 resolving issue with the (DB) transaction boundary being at the wrong level for price adjustments.

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/commands/BulkPriceUpdateCommands.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjuster.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/auditing/PriceMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjusterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
**Changes:**
Non-functional change.
Refactoring naming to be consistent around price adjustments.  All references to 'uplift' now refer to 'adjustment' instead.
> P4-3084 non-functional changes, rename changes only for consistency. References of 'uplift' changed to 'adjustment' for price adjustments.

- calculate-journey-variable-payments-suppressions.xml
**Changes:**
Minor change (suppression) for CVE that does not affect CJVP.  There is no update available for this transitive dependency.
> P4-3084 supressing false positve OWASP lang tag.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjuster.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustment.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustmentRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/main/resources/db/migration/ddl/V1_12__add_multiplier_and_effective_year_columns_to_price_adjustments.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/AnnualPriceAdjusterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/price/PriceAdjustmentRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsServiceTest.kt
**Changes:**
Small change to add extra columns to the price adjustment for alerting purposes.
An example of this would be a bulk price adjustment is in progress and we want to display a message on the UI to inform the end users.
> P4 3086 add new columns for price adjustment

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/BulkPriceUpdateCommands.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/PriceHistoryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/AnnualPriceAdjustmentMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/AuditEventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/PriceMetadata.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/main/resources/templates/annual-price-adjustment.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/AnnualPriceAdjustmentMetadataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewAllMoveTypesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
**Changes:**
- Adding price adjustment history tab to the price adjust page/view.
- Bumping number of allowed decimal points from 3 to 4 for the price adjustment rate.
See example screenshot below:
> P4 3009 display price adjustment history feature

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ManageJourneyPriceCatalogueController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ModelMapDecorator.kt
- src/main/resources/templates/annual-price-adjustment-history.html
- src/main/resources/templates/annual-price-adjustment.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManagePricesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
**Changes:**
Price adjustments can only be run for the current effective year or later.  Anything prior to this upon navigation to the price adjustments page the user will only see the price adjustments history.
Example screenshot below:
> P4 3122 only show adjustment history if prior to current effective year

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AnnualPriceAdjustmentsServiceTest.kt
**Changes:**
Updating the frontend and backend validation to tighten up the logic around price submission/changes.  A zero price will cause the spreadsheet download to fail.
Also put some (sensible?) limits on the max values allowed for prices and price adjustments.
What his boils down to is as follows:
Min  journey price 0.01
Max journey price 9999.99
Max adjustment rate 9.9999
> P4-3176 tightening up validation around price submissions. There was a bug in the front end controller allowing zero prices through.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ModelMapDecorator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingService.kt
- src/main/resources/templates/add-price.html
- src/main/resources/templates/update-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/SupplierPricingServiceTest.kt
**Changes:**
This changes the warnings that are display to a user when adding or updating prices depending on the contractual the price is being added or updated.
**Note: the same logic applies in the update screens.**
> P4 3095 add price warnings feature

- helm_deploy/calculate-journey-variable-payments/templates/_envs.tpl
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/GlobalController.kt
- src/main/resources/static/style.css
- src/main/resources/templates/layout/base.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
**Changes:**
Add an application wide feedback link to the bottom of all pages from the dashboard on-wards.  Note for development and pre-prod the links will not go anywhere.  This pulls in an env variable from the Kubernettes config (which you cannot see in this PR).
> P4-3155 changes to include the application survey feeback link on all pages from the dashboard onwards.

- src/main/resources/static/style.css
**Changes:**
Adding missing GDS transport font for the feedback link/footer.
> P4-3155 adding missing font for feedback link in page footer.

- src/main/kotlin/db/migration/data/dev/R__2_5_Integration_test_data.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/AnnualBulkPriceAdjustmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManageLocationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManagePricesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ViewAllMoveTypesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/IntegrationTestDataFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/SelectMonthYearPage.kt
**Changes:**
The fixture data for the integration tests was due a bit of a rethink having noticed some temporal related issues in the CI pipeline.
Previously the move fixture data was actually being set up for the present day.  Whilst the application technically won't grumble about this it is not how it works in practice.  All move data loaded into the real application is historic with the most recent data being the previous days moves.
Move data is priced on a month by month basis.  Any moves that start on the last day of the month and go into the next month fall within the following months prices.  To avoid this complication and ease integration testing I have changed it so the move fixture data starts on the first day of the previous month and stays within that month.
The integration …
> P4 3147 refactoring integration test data

- .circleci/config.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/JourneyService.kt
- src/main/resources/templates/journeys.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/IntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/ManageLocationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/ApplicationPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/IntegrationTestDataFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/JourneysForReviewPage.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/JourneyServiceTest.kt
**Changes:**
On the journeys for review page there was no natural ordering.  This means journeys starting from the same location can be scattered throughout the results on the page.  User feedback has informed us this makes their day to day work harder as they focus on a location at a time.
With these changes results will now be ordered, see attached screenshot as an example:
> P4-3127 updates to journeys for review so they are now ordered to make management of them easier for the end user.

- Dockerfile
**Changes:**
Small update to Dockerfile to reduce chances of Trivvy scan security failures.  The change will pull down OS updates when built to reduce potential wait time for image container is based on to be updated instead.
> Update Dockerfile to pull down OS patches faster to reduce Trivvy scan failures.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceException.kt
- src/main/resources/db/migration/ddl/V1_13__add_table_price_exceptions.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceExceptionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceTest.kt
**Changes:**
Introduces the concept of price exceptions at the domain level. This is purely in the backend. As of yet there is no supporting service or front end to add or remove these, this will be added later.
A price exception allows for supplier journey prices to be overridden for a fixed period of a month in a given effective year.  For a given price there can be up to 12 price exceptions in that year (though this is extremely unlikely).
Addition and removal of exceptions is handled by its aggregate root entity 'Price'.
> P4 3206 price exceptions domain

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/JourneyQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MoveQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MoveQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/MoveServiceTest.kt
**Changes:**
The purpose of this change is to use price exceptions in place of prices for a given month if there are any.
It contains updates to the queries that aggregate/pull back prices in the custom SQL (non JPA) repositories and any areas impacted by the change.
> P4-3214 intiial commit to update repository queries to factor in price exceptions and update code impacted by the change.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/PriceSheet.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/SupplierPricesSheet.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/PriceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/SupplierPricesSheetTest.kt
**Changes:**
Price exceptions are included in the JPC price book tab of the outputted spreadsheet where applicable for the month at which the spreadsheet is generated.
> P4-3219 update to include price exceptions in the outputted spreadsheet prices tab.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/resources/templates/update-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
**Changes:**
Small change to prevent adding price exceptions with the same price as the actual price (as this does not make sense). This is enforced at the Domain level so needs to be enforced here otherwise it will not be handled gracefully.
> P4-3209 add front end validtion to prevent adding a price exception the same price as the actual price.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/resources/templates/fragments/contractual-year.html
- src/main/resources/templates/fragments/flash-messages.html
- src/main/resources/templates/update-price.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
**Changes:**
- Tweaks to the layout and navigation around addition of price exceptions.
- Resized heading for contractual year, overly large and causing it to wrap.
- Heading for contractual year also included in the update price page to aid the user.
On the update price tab now says existing price exceptions:
On the price exceptions tab, move existing exceptions to top:
When you add an exception it stays on the tab instead of navigation to another page.
> P4 3209 price exceptions tab feature v2

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationInformationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/main/resources/templates/fragments/flash-messages.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationInformationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingControllerTest.kt
**Changes:**
The point at which price lock down message is displayed has been changed. Now displayed as soon at you go to the dashboard (and stays there) so clearer to end user.
> P4-3223 changed point at which price lock down message is displayed.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ControllerExtensionFunctions.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/MaintainSupplierPricingController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/MovePriceExceptionTest.kt
**Changes:**
This now uses the latest version of Spring boot (which in turn resolves a CVE) which is pulled in via the hmpps.gradle-spring-boot plugin.
It also fixes an issue with a date dependent integration test.
> P4-3299 updating 3rd party dependencies and correcting hardcoding of month in date dependent integration test.

- helm_deploy/values-prod.yaml
**Changes:**
This is to enable the feature (prior to the actual removal of the toggle entirely) so we can have it enabled in production.
> P4-3280 enabling the feature so can have an enabled released version prior to removal of the feature toggle.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/JpcApplication.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/InterceptorsConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/interceptors/SessionCookieInterceptor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/interceptors/SessionCookieProperties.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/interceptors/SessionCookieInterceptorTest.kt
**Changes:**
This is the first change of two related to SSO.  This particular change improves the cookie security.
In particular the key changes being setting the http-only attribute and max-age of the cookie.
> P4 3281 single sign on and off

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/interceptors/SessionCookieInterceptor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/interceptors/SessionCookieProperties.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/HtmlControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/interceptors/SessionCookieInterceptorTest.kt
**Changes:**
Tweaking how cookie 'secure' attribute is being set.  Did not work as expected even though documentation suggested otherwise.
> P4-3281 changing how secure attibute is set. Did not work as expexcted when tested over HTTPS connection.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/PriceSheet.kt
- src/main/resources/templates/annual-price-adjustment.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/AnnualPriceAdjustmentsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/AnnualBulkPriceAdjustmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/integration/pages/AnnualPriceAdjustmentPage.kt
**Changes:**
- Housekeeping to bump 3rd party dependencies.  This has helped clean up 3rd party CVE transitive dependency overrides.
- Bumping the number of allowed decimals from 4 to 15 for annual price adjustments.  It turns out this level of accuracy is required. 
Whilst there is no financial impact to the change itself, there is a financial impact to the Supplier, as they will not be fairly compensated for the journeys they complete as Indexation would not have been properly applied to the journeys.
> P4 3334 price adjustment increase decimal points

- build.gradle.kts
The change comes on the back of the Verracode pipeline issue the day before.  The OWASP job is also now failing for the same thing.
Moving to the next version or the DPS Gradle spring boot plugin should resolve this.  I have run the check locally before after pulling in this version and it gives the all clear.
> P4-3393 pull in latest DPS gradle spring boot plugin to suppress Log4j CVE.

- build.gradle.kts
Revolving the following security alerts for netty, log4j and h2 in-memory DB.
```
h2-1.4.200.jar (pkg:maven/com.h2database/h2@1.4.200, cpe:2.3:a:h2database:h2:1.4.200:*:*:*:*:*:*:*) : CVE-2021-23463
netty-buffer-4.1.69.Final.jar (pkg:maven/io.netty/netty-buffer@4.1.69.Final, cpe:2.3:a:netty:netty:4.1.69:*:*:*:*:*:*:*) : CVE-2021-43797
netty-codec-4.1.69.Final.jar (pkg:maven/io.netty/netty-codec@4.1.69.Final, cpe:2.3:a:netty:netty:4.1.69:*:*:*:*:*:*:*) : CVE-2021-43797
netty-codec-dns-4.1.69.Final.jar (pkg:maven/io.netty/netty-codec-dns@4.1.69.Final, cpe:2.3:a:netty:netty:4.1.69:*:*:*:*:*:*:*) : CVE-2021-43797
netty-codec-http-4.1.69.Final.jar (pkg:maven/io.netty/netty-codec-http@4.1.69.Final, cpe:2.3:a:netty:netty:4.1.69:*:*:*:*:*:*:*) : CVE-2021-43797
netty-codec-http2-4.1.69.Final.jar …
```
> P4-3394 fix CVE warnings for log4j, netty and h2 database.

- src/main/resources/db/migration/dml/V1_15__add_quotes_to_multiplier_value_for_audit_events.sql
So testing on DEV highlighted an issue that I was not able to easily recreate as integration tests start with a clean audit history for bulk price adjustments.
The application was not able to go to the price adjustment screen as it was not able to de-serialise old audit records for bulk price adjustments. A runtime error was occurring.
This change adds quotes around any existing multiplier values to support the change to BigDecimal.
**So this:**
`{"supplier" : "SERCO", "effective_year" : 2021, "multiplier" : 1.5, "details" : "some notes"}`
**Would be updated to this:**
`{"supplier" : "SERCO", "effective_year" : 2021, "multiplier" : "1.5", "details" : "zzz"}`
**Upon navigating to the appropriate page the user should see something like the following:**
> P4-3392 migration to correct old price adjustment audit records.

- build.gradle.kts
**Temporary overrides for the following security warnings:**
`log4j-api-2.16.0.jar (pkg:maven/org.apache.logging.log4j/log4j-api@2.16.0, cpe:2.3:a:apache:log4j:2.16.0:*:*:*:*:*:*:*) : CVE-2021-44832, CVE-2021-45105
log4j-to-slf4j-2.16.0.jar (pkg:maven/org.apache.logging.log4j/log4j-to-slf4j@2.16.0, cpe:2.3:a:apache:log4j:2.16.0:*:*:*:*:*:*:*) : CVE-2021-44832, CVE-2021-45105
logback-classic-1.2.6.jar (pkg:maven/ch.qos.logback/logback-classic@1.2.6, cpe:2.3:a:qos:logback:1.2.6:*:*:*:*:*:*:*) : CVE-2021-42550
logback-core-1.2.6.jar (pkg:maven/ch.qos.logback/logback-core@1.2.6, cpe:2.3:a:qos:logback:1.2.6:*:*:*:*:*:*:*) : CVE-2021-42550
`
> P4-3404 temporary version overrides for 3rd party libraries with logging CVE warnings.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MoveQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/PricesSpreadsheetGenerator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/outbound/PricesSpreadsheetGeneratorTest.kt
Fixes a bug whereby the redirections and long hauls moves where displayed the wrong way round on the generated spreadsheet.
> P4-3407 fix whereby redirections were being shown on the the long haul tab and long haul on the redirections tab.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/util/json/BigDecimalParser.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/PriceMetadataTest.kt
I identified a problem when trying to make a change to a price whereby if there was an historic audit record for the chosen price it can cause a runtime exception.
This is down for a format change.  It was stored as a double but now as a string.
This change adds support for both the old and new format change.
> P4-3435 fixing issue parsing historic audit events for price changes.

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/CommandRunner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/HistoricMovesCommand.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/ReportImportCommand.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/CommandRunnerPeopleAndProfilesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/ReportImportCommandTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
This adds a new backfill command for people and profiles only.  This can be done independently of moves.
This does not answer the question over why we are missing people/profiles.  Either way we need this to resolve the historic moves that are missing them.
> P4-3476 adding command so can backfill people and profiles independantly of moves.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/TaskScheduler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/PreviousDaysLocationMappingTask.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/PreviousDaysMovesTask.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/PreviousDaysPeopleAndProfilesTask.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/BackfillReportsTaskTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/PreviousDaysMovesTaskTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/PreviousDaysPeopleAndProfilesTaskTest.kt
The change splits out the import of people and profiles to run separately from that of moves in an effort to reduce memory consumption when there is a large volume of reporting data.
There is also a small amount of refactoring around the existing tasks to tidy them up a bit.
> P4-3476 split import of people and profiles out from moves to help reduce memory consumption when high volumes of reporting data.

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/PersistenceResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/PersonPersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/inbound/report/ReportImporter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/spreadsheet/inbound/report/ReportParser.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/PersonPersisterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/ImportServiceTest.kt
This changes the importing process for both people and profiles to be sequence (stream) based to help with memory consumption when we have large volumes of data.
This does not get round the fact due to ongoing backfill we have some very large files being processed e.g. 195MB for a profiles file (of which was about 54k individual profiles).
> P4 3476 improve memory consumption usage

- .env
- docker-compose-cjvp.yml
- docker-compose.yml
- src/main/resources/application-dev.yml
As far as I can tell this mode isn't necessary as we already expose the ports of the dependant services. Without it, I've got the service running locally and the integration tests passing.
> Stop using host Docker network mode

- .github/CODEOWNERS
This team contains only developers and means we'll automatically be asked to review any PRs.
> Assign PECS Developers as code owners

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MoveQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/moves/HistoricMovesProcessingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/moves/MoveService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/reports/MoveFilterer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MoveQueryRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/moves/HistoricMovesProcessingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/reports/ImportServiceIntegrationTest.kt
Whilst carrying out move corrections on the preprod and production environments I realised moves without move types were not being included when they should have been.
The historic move processing service has now been changed to now include all moves with and without a move type.
> P4-3561 this changes the historic move processing service to include moves that have not been assigned a move type. They were previously ignored.

- .circleci/config.yml
Chore:
Set the OWASP cache to be inline with changes to the shared HMPPS Circle CI orb.  This should resolve the following:
> P4-3579 set the OWASP cache to be inline with changes to the shared HMPPS Circle CI orb.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/journey/JourneyQueryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MoveQueryRepository.kt
So on comparing results with changes deployed to preprod versus what was in production I noticed a couple of multi type moves were not displaying as expected for Feb 2022 and Mar 2022.
Ultimately this is a result of poor seed data, either way it should still show up in the multi moves so they can at least be investigated and ideally resolved the by the suppliers.
With the two additional fields now present on the moves table (month and year) we only need to check for the presence of an end date and not if it is in range, the month and year fields service this purpose.
> P4-3559 tweak to queries as the date restriction needs have changed due to have month and year as columns on the moves tables.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/event/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MovePersister.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/reports/MoveFilterer.kt
- src/main/resources/templates/fragments/event-type.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/reports/MoveFiltererTest.kt
This removes all references to the JourneyLockout event which has been deprecated in the Basm API.
This is a safe removal as there are no such events recorded at the time of raising the PR.
> P4-3558 removing journey lockout event which is no longer used by Basm.

- run.sh
This change has been recommended by the Cloud Platform team.  In theory it will improve the garbage collection of the containers running JVM's in the cluster.  See image below. Having verified this in production we will be affected by this.
> P4-3604 changing the container configuration to run as server class machine as recommended by cloud platform.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/SummaryPageController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/MoveRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/moves/MoveService.kt
- src/main/resources/templates/move.html
- src/main/resources/templates/moves-by-type.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/SummaryPageControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/move/TestMoveFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/moves/MoveServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/reports/ImportServiceIntegrationTest.kt
The main dashboard page provides the ability to search for moves by their reference number.
The breadcrumb trail was displaying incorrectly after searching for a move that was not in the same month as the currently chosen month on the dashboard view. It showed the month chosen on the dashboard and not that of the move.
Additional changes have also been made to the move type link in the breadcrumbs as this also would not have gone to the correct month/year.
**Breadcrumb trail before (notice the move start date is Dec 1st 2020 and not in April 2022):**
**Breadcrumb trail after:**
> P4 3564 breadcrumb trail bug

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/filters/ChooseSupplierFilter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/config/filters/ChooseSupplierFilterTest.kt
I noticed when looking at the logs calls to the health endpoints are being redirected to the choose supplier URL.  I think primarily this has not been noticed as we don't have any type of pingdom set up for the service.
> P4-3738 this is a short term fix to resolved the health check endpoints of the service, calls are being redirected to the choose supplier URL

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationInformationController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/controller/ApplicationInformationControllerTest.kt
If the reporting feed is two or more days out of date then the users will be presented with a banner message informing them of the fact.
See screenshot example below:
If such issues have occurred with the feed in an ideal world it should have been resolved.  This is belt and braces.
> P4-3722 display a banner message to the user if the pricing data is two or more days out of date. This is to alert them of any potential feed issues.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/ImportReportsDataTask.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/tasks/ImportReportsDataTaskTest.kt
Testing in development highlighted a gap in the auto recovery from a failed ingress. Missing import on date 2022-06-18.
> P4-3722 resolves an issue where by was not starting at the correct date when resuming from a failed report ingress.

- build.gradle.kts
Chore: bumping 3rd party dependencies primarily to resolve owasp warnings.
> P4-3782 bumping 3rd party dependecies to latest versions where applicable.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/CommandRunner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/DailyReportsImporterRunner.kt
- src/main/resources/application-daily-reports.yml
Prep work to for the upcoming k8 job so can run the daily reports import upon starting the container based application which will get pulled down as part of the job.
Essentially what we are going to end up with is this in the job:
`java -jar app.jar --spring.profiles.active=daily-reports`
> P4-3764 initial commit to add the daily imports runner and associated profile which will be used by the k8 job.

- build.gradle.kts
After running `./gradlew dependencyCheckAnalyze` to see a report of the OWASP security check, it was failing and produced an error around `aws-java-sdk-s3-1.12.252.jar (pkg:maven/com.amazonaws/aws-java-sdk-s3@1.12.252) : CVE-2022-31159` so I upgraded this version from `1.12.252 ` to `1.12.266` to silence the error. In addition I upgraded DPS gradle spring boot from `4.3.2` to `4.3.3`
The steps used for this ticket:
```
// This will report if the OWASP security check is failing (which it should be)
$ ./gradlew dependencyCheckAnalyze
// This will give you some of idea of what 3rd party libraries can be updated
$ ./gradlew dependencyUpdates
// This should be run after updating 3rd party libraries to see if security warnings go away.
$ ./gradlew dependencyCheckAnalyze
// This will run the …
```
> Update to latest version of DPS gradle spring boot and aws-java-sdk-s3

- helm_deploy/values-preprod.yaml
- k8_jobs/import-reports.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/DailyReportsImporterRunner.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/cli/DailyReportsImporterRunnerTest.kt
The daily importer has been updated to support back filling should the need arise.
This change also now disables the old way the import is run on preprod as the intent is to now move to the k8 cron job instead.
> P4-3764 disable application task for testing of k8 replacemet task/job in preprod and add support for back dating reports.

- Dockerfile
Reverts ministryofjustice/calculate-journey-variable-payments#490
> Revert "P4-3832 moving to a new Java docker image as the Open JDK version is now deprecated and no longer receiving updates."

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/auditing/AuditableEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/reports/ImportReportsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/AuditServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/reports/ImportReportServiceTest.kt
This should help resolve a self repair issue whereby an import didn't work fully e.g. it only imported moves and people and not profiles. Previously the service regarded this as successful due to audit records existing for the moves and people imported. Now only one audit event for an import will only be created if all 3 are successfully imported so any attempts for the service to self repair will work from the date of the last successful audit entry.
> P4-3764 only audit reports import if move, people and profiles imported without error. This indicates a successful import.

- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/domain/price/Price.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/pricing/PriceImporter.kt
- src/main/resources/db/migration/dml/V1_21__backfill_price_audit_events.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/pecs/jpc/service/pricing/ImportPricesServiceIntegrationTest.kt
Changes to fix an issue whereby audit records were not being created due to the lazy load of locations on price entities causing a runtime error.
> P4-3865 fixing issue where audit events were not being created as part of the bulk price upload process.
